name: Delete Merged Branch on PR Close

on:
  pull_request:
    types: [closed]

jobs:
    delete-merged-branch:
        runs-on: ubuntu-latest
        steps:
          - name: Delete Merged Branch
            uses: rtCamp/action-delete-branch@v2.0.0
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}